build: upgrade to C++23
All of the OpenBMC projects now utilize C++23. Not using it results in
a fail of a local meson build.
"""
../subprojects/sdbusplus/include/sdbusplus/bus/match.hpp: In function
‘constexpr auto sdbusplus::bus::match::rules::interfacesAddedAtPath
(std::string_view)’:
../subprojects/sdbusplus/include/sdbusplus/bus/match.hpp:148:1: error:
call to non-‘constexpr’ function ‘auto sdbusplus::bus::match::
rules::argNpath(size_t, std::string_view)’ [-Werror=invalid-constexpr]
"""
Upgrade the build to use C++23 and effectively solving the issue above.

Tested:
"meson setup build && cd build && meson compile" finishes successfully.

Change-Id: I4fe219d5e7786fe5e07be502cfbe108e44a1ad9b
Signed-off-by: Konstantin Aladyshev <aladyshev22@gmail.com>